default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_photoapp_development

test:
  <<: *default
  database: my_photoapp_test

production:
  <<: *default
  database: my_photoapp_production
