development:
  adapter: postgresql
  database: my_photoapp_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_photoapp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_photoapp_production
  pool: 5
  timeout: 5000
